version: "3.9"

services:
  app:
    build: .
    container_name: carpet-app
    depends_on:
      - mongo
      - kafka
    environment:
      # Spring Boot will read these environment variables
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: carpetdb

      # if we later add KafkaTemplate, Spring can use this.bootstrap-servers
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    ports:
      - "8080:8080"

  mongo:
    image: mongo:7
    container_name: carpet-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: carpet-zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: carpet-kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ENABLE_KRAFT: "no"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

volumes:
  mongo_data:
